### ISSUE TITLE
Consider using a namespace instead of a class

### ISSUE THREAD

**Issue by veigaribo** [rafabulsing/decision-table#1]
Perhaps there is a reason for it I'm not seeing, but, since all the DecisionTable methods are static, does it make sense to think of it as a class?

**Comment by rafabulsing** [comment]
Great question!

The intention behind that is to eventually make it possible to instantiate a fully configured table. That way, if you had to use one multiple times in your code, you could configure it once, and then just call `set()` or `do()` as you wish.

I started with the static version just cause I figured that that was the easier part :p

**Comment by Veigaribo** [comment]
Alright, looking forward to that o/
